name: Deploy Firebase Functions

on:
  push:
    branches: ['main']
    paths: ['functions/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      - name: Install dependencies
        run: npm ci --prefix functions

      - name: Build functions
        run: npm run build --prefix functions

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v14.17.0
        with:
          args: deploy --only functions --force
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUDIENCE_REACTIONS_PROD }}
